export { default as LogoIcon } from "@/public/images2/vectors/logo.png";
export { default as MainIcon } from "@/public/images2/vectors/icon.png";
export { default as UnionIcon } from "@/public/images2/vectors/Union.png";
export { default as CardIcon } from "@/public/images2/vectors/Card.png";
export { default as WifiIcon } from "@/public/images2/vectors/wifi.png";
export { default as PlayIcon } from "@/public/images2/vectors/play.png";
export { default as RoomIcon } from "@/public/images2/vectors/room.png";
export { default as ParkIcon } from "@/public/images2/vectors/park.png";
export { default as ChairIcon } from "@/public/images2/vectors/chair.png";
export { default as BusIcon } from "@/public/images2/vectors/bus.png";
export { default as GroupIcon } from "@/public/images2/vectors/group.png";
export { default as TVIcon } from "@/public/images2/vectors/tv.png";
export { default as FooterLogoIcon } from "@/public/images2/vectors/logo-footer.png";
export { default as FacebookIcon } from "@/public/images2/vectors/fb.png";
export { default as InstagramIcon } from "@/public/images2/vectors/insta.png";
export { default as LocationIcon } from "@/public/images2/vectors/location.png";
export { default as CallIcon } from "@/public/images2/vectors/call.png";
export { default as SMSIcon } from "@/public/images2/vectors/sms.png";
export { default as MenuIcon } from "@/public/images2/vectors/icon_menu.png";
export { default as Location2Icon } from "@/public/images2/vectors/location2.png";
export { default as Call2Icon } from "@/public/images2/vectors/call2.png";
export { default as SMS2Icon } from "@/public/images2/vectors/sms2.png";
export { default as USFlagIcon } from "@/public/images2/vectors/us_flag.png";
export { default as CzechFlagIcon } from "@/public/images2/vectors/cz_flag.png";

export { default as HomeImage1 } from "@/public/images2/gallery2/1-home.png";
export { default as HomeImage2 } from "@/public/images2/gallery2/2-home.png";
export { default as HomeImage3 } from "@/public/images2/gallery2/3-home.png";
export { default as HomeImage4 } from "@/public/images2/gallery2/4-home.png";

export { default as ShowerIcon } from "@/public/images2/vectors/shower.png";
export { default as TV2Icon } from "@/public/images2/vectors/tv2.png";
export { default as ToiletIcon } from "@/public/images2/vectors/toilet.png";
export { default as FridgeIcon } from "@/public/images2/vectors/fridge.png";
export { default as BreakfastIcon } from "@/public/images2/vectors/breakfast.png";
export { default as BowlIcon } from "@/public/images2/vectors/bowl.png";
export { default as Bus2Icon } from "@/public/images2/vectors/bus2.png";
export { default as LaundaryIcon } from "@/public/images2/vectors/laundary.png";
export { default as TV3Icon } from "@/public/images2/vectors/tv2.png";
export { default as FrontIcon } from "@/public/images2/vectors/front.png";
export { default as ProfileIcon } from "@/public/images2/vectors/profile.png";

export { default as AccomImage1 } from "@/public/images2/gallery2/1room.jpg";
export { default as AccomImage2 } from "@/public/images2/gallery2/2room.jpg";
export { default as AccomImage3 } from "@/public/images2/gallery2/3room.jpg";
export { default as AccomImage4 } from "@/public/images2/gallery2/4room.jpg";
export { default as AccomImage5 } from "@/public/images2/gallery2/5room.jpg";
export { default as AccomImage6 } from "@/public/images2/gallery2/6room.jpg";
export { default as AccomImage7 } from "@/public/images2/gallery2/7room.jpg";
export { default as AccomImage8 } from "@/public/images2/gallery2/8room.jpg";

export { default as SerImage1 } from "@/public/images2/gallery2/ser1.png";
export { default as SerImage2 } from "@/public/images2/gallery2/ser2.png";
export { default as SerImage3 } from "@/public/images2/gallery2/ser3.png";
export { default as SerImage1Resp } from "@/public/images2/gallery2/ser1_resp.png";
export { default as SerImage2Resp } from "@/public/images2/gallery2/ser2_resp.png";
export { default as SerImage3Resp } from "@/public/images2/gallery2/ser3_resp.png";

export { default as SerIcon1 } from "@/public/images2/vectors/icon (1).png";
export { default as SerIcon2 } from "@/public/images2/vectors/icon (2).png";
export { default as SerIcon3 } from "@/public/images2/vectors/icon (3).png";
export { default as SerIcon4 } from "@/public/images2/vectors/icon (4).png";
export { default as SerIcon5 } from "@/public/images2/vectors/icon (5).png";
export { default as SerIcon6 } from "@/public/images2/vectors/icon (6).png";
export { default as SerIcon7 } from "@/public/images2/vectors/icon (7).png";
export { default as SerIcon8 } from "@/public/images2/vectors/icon (8).png";
export { default as SerIcon9 } from "@/public/images2/vectors/icon (9).png";
export { default as SerIcon10 } from "@/public/images2/vectors/icon (10).png";
export { default as SerIcon11 } from "@/public/images2/vectors/icon (11).png";

export { default as SurImage1 } from "@/public/images2/gallery2/sur1.png";
export { default as SurImage2 } from "@/public/images2/gallery2/sur2.png";
export { default as SurImage3 } from "@/public/images2/gallery2/sur3.png";
export { default as SurImage4 } from "@/public/images2/gallery2/sur4.png";
export { default as SurImage5 } from "@/public/images2/gallery2/sur5.png";
export { default as SurImage6 } from "@/public/images2/gallery2/sur6.png";
export { default as SurImage1Resp } from "@/public/images2/gallery2/sur1_resp.png";
export { default as SurImage2Resp } from "@/public/images2/gallery2/sur2_resp.png";
export { default as SurImage3Resp } from "@/public/images2/gallery2/sur3_resp.png";
export { default as SurImage4Resp } from "@/public/images2/gallery2/sur4_resp.png";
export { default as SurImage5Resp } from "@/public/images2/gallery2/sur5_resp.png";

export { default as Location2Icon } from "@/public/images2/vectors/location2.png";
export { default as Call2Icon } from "@/public/images2/vectors/call2.png";
export { default as SMS2Icon } from "@/public/images2/vectors/sms2.png";
