import "./globals.css";
import { useTranslations } from "next-intl";
import { redirect } from "next/navigation";
import { Urbanist } from "next/font/google";

import { locales } from "@/navigation";

import Navbar from "@/Components/Other/Navbar/Navbar";
import Footer from "@/Components/Other/Footer/Footer";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Penzion Atrium",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  const t = useTranslations("Contact");
  if (!locales.includes(locale)) {
    redirect("/");
  }

  console.log(t("emails"));

  return (
    <html lang={locale}>
      <body className={urbanist.className}>
        <Navbar />
        {children}
        <Footer emails={t("emails")} />
      </body>
    </html>
  );
}
